package org.dimensinfin.android.mvc.domain;

public enum SpacerType {
	DEFAULT, LINE_WHITE, LINE_RED, LINE_ROSE, LINE_ORANGE, LINE_YELLOW, LINE_GREEN, LINE_LIGHTBLUE, LINE_DARKBLUE,
	LINE_PURPLE, LINE_GREY, LINE_BLACK, EMPTY_SIGNAL
}
